### ISSUE TITLE
The request will show 401 error when I set the accessTokenFormat to OAuth2TokenFormat.REFERENCE

### ISSUE THREAD

**Issue by Waylon-Firework** [spring-projects/spring-authorization-server#1014]
**Describe the bug**

The request with postman(Bearer token in the header) will show 401 error when I set the accessTokenFormat to OAuth2TokenFormat.REFERENCE

Could you please provide a demo with .accessTokenFormat(OAuth2TokenFormat.REFERENCE).

```
                .tokenSettings(
                        TokenSettings.builder()
                                .accessTokenTimeToLive(Duration.ofMinutes(30L))
                                .accessTokenFormat(OAuth2TokenFormat.REFERENCE)
                                .reuseRefreshTokens(true)
                                .refreshTokenTimeToLive(Duration.ofDays(30L))
                                .idTokenSignatureAlgorithm(SignatureAlgorithm.RS256).build()
                )
```

**Comment by Waylon-Firework** [comment]
I have to add this config to yml:

```
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:7878/oauth2/introspect
          client-id: my-client-id
          client-secret: my-client-password
```
