### ISSUE TITLE
Add release automation with reusable workflows

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-authorization-server#1427]
Reusable GitHub Actions workflows are available in [spring-io/spring-security-release-tools](https://github.com/spring-io/spring-security-release-tools), including an automated release workflow. For example, the following will reuse a workflow for building the code, defined in `build.yml`:

```yaml
name: Build

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@v1
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [17]
    with:
      runs-on: ${{ matrix.os }}
      java-version: ${{ matrix.jdk }}
      distribution: temurin
    secrets: inherit
```
