### ISSUE TITLE
Token exchange failed when the subject token is a client_credentials granted access token 

### ISSUE THREAD

**Issue by wapkch** [spring-projects/spring-authorization-server#1691]
**Describe the bug**
Token exchange failed when the subject token is a client_credentials granted access token.

**To Reproduce**
1. build a spring authorization server which enables client_credentials grant for 'user-client' and token-exchange grant for 'messaging-client'
```yml
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          test-client:
            registration:
              client-id: "user-client"
              client-secret: "{noop}user"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - user.read
          token-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}messaging"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - urn:ietf:params:oauth:grant-type:token-exchange
              scopes:
                - message.read
```
2. get access token for 'user-client' using client_credentials grant
3. build resource server  'user-service' and 'messaging-service', user-service remote calls messaging-service
4. Access resource server 'user-service' with the access token above 
5. token exchange failed due to the client_credentials granted access token does not have a 'princial' attribute, but OAuth2TokenExchangeAuthenticationProvider require a principal to be available via the subject_token for impersonation or delegation use cases:

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/5d3e58b9-3be4-4da6-b5f2-996723cf56ba">

**Expected behavior**
As per https://datatracker.ietf.org/doc/html/rfc8693，there doesn't appear to be any explicit prohibition against using an access token obtained through the client_credentials grant for token exchange.
